### ISSUE TITLE
xor_resnet error

### ISSUE THREAD

**Issue by iwyoo** [sunggukcha/xor#1]
1. Typo
https://github.com/sunggukcha/xor/blob/aadb388ea285613eee4d527fcc6ecab1afc292eb/xor_resnet.py#L157

2. self in staticmethod
https://github.com/sunggukcha/xor/blob/master/xor_resnet.py#L30
It seems that autograd.Function is not proper in this implementation. Check https://discuss.pytorch.org/t/difference-between-apply-an-call-for-an-autograd-function/13845/13

**Comment by sunggukcha** [comment]
Thanks for your comment.
I fixed such issues and saw it running in classification problem.  You can see the example here https://github.com/sunggukcha/pascal2007
