### ISSUE TITLE
Are there some training results?

### ISSUE THREAD

**Issue by creaitr** [sunggukcha/xor#3]
Actually, I'm also interested in this novel activation function.
If the ReaLU works well then we can expect a decrease in the computational complexity and the number of layers by using the ReaLU.
However, there are no training results in the README.
If you have tried some training, can you share the results of ReaLU?

**Comment by AhnJG** [comment]
Did you check the XOR activation.ipynb file?
Maybe you can find the result in there

**Comment by sunggukcha** [comment]
I experimented on the Caltech 101 classification task with ReLU, ReaLU, and ReaLU6. ReaLU6 is a version which has 6 as a threshold. 
Without ImageNet pretrain, ReLU and ReaLU resulted in very similar score (63% top-1 score), while ReaLU6 resulted (62% top-1 score).
